name: nlpbook
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyterlab
  - matplotlib
  - nltk
  - numpy
  - pandas
  - pip
  - pytorch
  - requests
  - scikit-learn
  - scipy
  - seaborn
  - spacy
  - torchvision
  - tqdm
  - pip:
    - annoy
    - -e .
